### ISSUE TITLE
Support ILDA fonts

### ISSUE THREAD

**Issue by SpaceK33z** [Volst/laser-dac#3]
It should be possible to write text with a custom font to the laser.

**Comment by SpaceK33z** [comment]
The basics work now but the ILDA fonts are reversed. Need to figure out if this is  on purpose.

**Comment by elzekool** [comment]
Hey @SpaceK33z,

In CNC/Laser engraving designs "[Hershey Fonts](https://en.wikipedia.org/wiki/Hershey_fonts)" are very popular, most so due to the fact that it contains a single stroke font and can be downloaded freely (https://emergent.unpythonic.net/software/hershey). I think this fact also makes it very suitable for laser projection. Maybe this is something usefull to add to the @laser-dac/draw library?

I made simple proof of concept:
https://gist.github.com/elzekool/538efd2b8fbfc26123a73b6cccf74f62

That class/file can be used as following:
```typescript
import {DAC} from "@laser-dac/core";
import {Simulator} from "@laser-dac/simulator";
import {Scene} from "@laser-dac/draw";
import {HersheyFont, loadHersheyFont} from "./HersheyFont";
import * as path from 'path';

(async () => {
    const dac = new DAC();
    dac.use(new Simulator());

    await dac.start();

    const scene = new Scene();

    const font = loadHersheyFont(path.resolve(__dirname, './futural.jhf'));

    function renderFrame() {
        scene.add(new HersheyFont({
            x : 0.1,
            y : 0.1,
            font : font,
            text : 'Hello world!',
            charWidth : 0.05,
            spacingFactor : 0.8,
            color : [ 0, 0, 1 ]
        }));
    }

    scene.start(renderFrame);
    dac.stream(scene);
})();
```
This generates the following preview:

![image](https://user-images.githubusercontent.com/2158053/58828965-eb98c080-8646-11e9-93ed-ba40317bd571.png)

**Comment by SpaceK33z** [comment]
Oh that's very cool! I was struggling with finding good fonts so I kinda give up on this, but Hershey Fonts look good!!

**Comment by SpaceK33z** [comment]
If you make a PR, could you also remove `IldaFont` with it? It's not necessary after that anymore, it's kindof a failed experiment (I haven't found good ILDA fonts).
